; The Hero Chronicles Loot Manager defaults.
; Personal choices are stored locally in THCLoot\settings.ini and are never overwritten by patching.
[Window]
Theme=0
Opacity=100
ShortLabels=0
[ImGui]
Width=366
Height=570
