# LootNScoot Item Rules
# Actions: None Keep Sell Tribute Bank Vault Destroy

[Settings]
DoNotDisturb=false
UseSmallPopup=false
AutoKeepBonus=false
Opacity=1
Accent=143,208,255
[Rules]

[Filters]

[IgnoreList]

[AutoPass]
