# LootNScoot Item Rules
# Actions: None Keep Sell Tribute Bank Vault Destroy

[Settings]
DoNotDisturb=false
UseSmallPopup=false
AutoKeepBonus=false
Opacity=1
Accent=143,208,255
[Rules]
Armadillo Husk=Sell|680|19195
Chunk of Meat=Sell|817|13085
Pristine Lizard Talon=Sell|1125|51292
Spiderling Silk=Keep|782|13099
Dark Colored Fungus=Sell|1233|51275
Rough Silk=Sell|782|34212
White Lizard Scale=Sell|1224|51282
Green Lizard Scale=Sell|1225|51281
Brown Lizard Scale=Sell|1223|51284
Froglok Meat=Sell|817|13409
Worn Great Staff (Enchanted)=Sell|602|1006012
Black Lizard Scale=Sell|1225|51280
Rusty Warhammer (Enchanted)=Sell|567|1006014
Brown Lizard Talon=Sell|1125|51290
Orange Lizard Scale=Sell|1224|51285
Bone Chips=Sell|804|13073
Large Cloth Shirt=Sell|678|1028
Coarse Silk=Sell|782|34211
Light Colored Fungus=Sell|1136|51276
Yellow Lizard Scale=Sell|1224|51283
Rusty Two Handed Sword (Enchanted)=Sell|519|1005023
Large Cloth Pants (Enchanted)=Keep|631|1001035
Multi-Colored Fungus=Sell|1106|51274
Rat Ears=Sell|793|13072
Rusty Long Sword (Enchanted)=Sell|590|1005019
Snake Scales=Sell|813|13070
Snake Fang=Sell|801|13067
Mesh Mantle=Keep|668|1145
Lizard Meat=Sell|817|13410
Pristine Lizard Scale=Sell|1225|51279
Large Cloth Wristband=Sell|638|1033
Bat Wing=Sell|791|13068
Giant Bat Wing=None|791|13062
Torch=None|547|13002
Woven Spider Silk=None|572|9914
Large Widow Abdomen=None|927|27534
Rusty Rapier=None|762|7008
Orc Skull=Sell|1070|16174
Large Sylvan Bat Fur=Sell|792|20272
Small Cloth Choker=Sell|500|1015
Orc Scalp=Sell|555|13791
Severed Orc Foot=Sell|743|9894
Silvril Ore=Sell|1095|34239
Orc Clavicle=Sell|907|19565
Large Raw-hide Shoulderpads=Sell|668|2165
Orc Ribcage=Sell|974|19551
Brick of Crude Bronze=Sell|1135|19697
Crushbone Belt=Sell|564|13318
Bandages=Sell|812|13009
Small Cloth Cord=Sell|572|1019
Small Raw-hide Shoulderpads=Sell|668|2153
Small Raw-hide Gloves (Enchanted)=Sell|636|1002158
Orc Ulna=Sell|905|16185
Small Cloth Shirt=Sell|678|1016
Small Cloth Shawl=Sell|665|1017
Crushbone Belt (Legendary)=Sell|564|2013318
Small Cloth Gloves=Sell|517|1022
Legionnaire's Bracer=Sell|637|2299
Raw Indigo Nihilite=Sell|1439|37858
Orc Eye=Sell|859|13266
Crushbone Belt (Enchanted)=None|564|1013318

[Filters]

[IgnoreList]

[AutoPass]
